#pragma once

class TraitConstants
{
public:
	/** AFFECT */
	static const int FIRST_LAYER_FIRST_TRAIT_AFFECT = 0;
	static const int SECOND_LAYER_FIRST_TRAIT_AFFECT_TYPE = 1;
	static const int THIRD_LAYER_FIRST_TRAIT_AFFECT_TYPE1 = 2;
	static const int FOURTH_LAYER_FIRST_TRAIT_DIRECT = 3;
	static const int THIRD_LAYER_FIRST_TRAIT_AFFECT_TYPE2 = 4;
	static const int FOURTH_LAYER_FIRST_TRAIT_SINGLE_TARGET = 5;
	static const int FOURTH_LAYER_FIRST_TRAIT_AREA_OF_EFFECT = 6;
	static const int FIFTH_LAYER_FIRST_TRAIT_RADIUS = 7;
	static const int FIFTH_LAYER_FIRST_TRAIT_POWER = 8;
	static const int SECOND_LAYER_SECOND_TRAIT_DAMAGE = 9;
	static const int THIRD_LAYER_FIRST_TRAIT_DAMAGE = 10;
	static const int THIRD_LAYER_FIRST_TRAIT_DAMAGE_TYPE = 11;
	static const int FOURTH_LAYER_FIRST_TRAIT_DAMAGE_TYPE1 = 12;
	static const int FIFTH_LAYER_FIRST_TRAIT_PHYSICAL = 13;
	static const int FIFTH_LAYER_FIRST_TRAIT_SUPERNATURAL = 14;
	static const int FOURTH_LAYER_FIRST_TRAIT_DAMAGE_TYPE2 = 15;
	static const int FIFTH_LAYER_FIRST_TRAIT_ELEMENTAL = 16;
	static const int SIXTH_LAYER_FIRST_TRAIT_FIRE = 17;
	static const int SIXTH_LAYER_FIRST_TRAIT_FROST = 18;
	static const int SIXTH_LAYER_FIRST_TRAIT_LIGHTNING = 19;
	static const int FIFTH_LAYER_FIRST_TRAIT_PSYCHIC = 20;
	static const int FIFTH_LAYER_FIRST_TRAIT_SOUND = 21;
	static const int FIFTH_LAYER_FIRST_TRAIT_KINETIC = 22;
	static const int FIFTH_LAYER_FIRST_TRAIT_ACID = 23;
	static const int FIFTH_LAYER_FIRST_TRAIT_BLEED = 24;
	static const int FIFTH_LAYER_FIRST_TRAIT_NECROTIC = 25;
	static const int FIFTH_LAYER_FIRST_TRAIT_HOLY = 26;
	static const int FIFTH_LAYER_FIRST_TRAIT_UNHALLOW = 27;
	static const int SECOND_LAYER_SECOND_TRAIT_HEALING = 28;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALING = 29;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALING_TYPE = 30;
	static const int FOURTH_LAYER_FIRST_TRAIT_RESTORATION = 31;
	static const int FOURTH_LAYER_FIRST_TRAIT_ABSORPTION = 32;


	/** STATS */
	static const int FIRST_LAYER_FIRST_TRAIT_STATS = 33;
	static const int SECOND_LAYER_FIRST_TRAIT_OFFENSIVE = 34;
	static const int THIRD_LAYER_FIRST_TRAIT_ATTACK_SPEED = 35;
	static const int THIRD_LAYER_FIRST_TRAIT_CAST_SPEED = 36;
	static const int THIRD_LAYER_FIRST_TRAIT_CRITICAL = 37;
	static const int FOURTH_LAYER_FIRST_TRAIT_CRITICAL_CHANCE = 38;
	static const int FIFTH_LAYER_FIRST_TRAIT_CRITICAL_CHANCE = 39;
	static const int FOURTH_LAYER_FIRST_TRAIT_CRITICAL_EFFECT = 40;
	static const int FIFTH_LAYER_FIRST_TRAIT_CRITICAL_EFFECT = 41;
	static const int THIRD_LAYER_FIRST_TRAIT_HIT_CHANCE = 42;
	static const int FIFTH_LAYER_FIRST_TRAIT_HIT_CHANCE = 43;
	static const int SECOND_LAYER_FIRST_TRAIT_DEFENSIVE = 44;
	static const int THIRD_LAYER_FIRST_TRAIT_EVASION = 45;
	static const int FOURTH_LAYER_FIRST_TRAIT_EVASION_CHANCE = 46;
	static const int THIRD_LAYER_FIRST_TRAIT_DODGE = 47;
	static const int FOURTH_LAYER_FIRST_TRAIT_DODGE_CHANCE = 48;
	static const int FOURTH_LAYER_FIRST_TRAIT_DODGE_REDUCTION = 49;
	static const int THIRD_LAYER_FIRST_TRAIT_BLOCK = 50;
	static const int FOURTH_LAYER_FIRST_TRAIT_BLOCK_CHANCE = 51;
	static const int FOURTH_LAYER_FIRST_TRAIT_BLOCK_REDUCTION = 52;
	static const int THIRD_LAYER_FIRST_TRAIT_ARMOUR = 53;
	static const int FOURTH_LAYER_FIRST_TRAIT_ARMOUR = 54;
	static const int SECOND_LAYER_FIRST_TRAIT_MOVEMENT_SPEED = 55;
	static const int SECOND_LAYER_FIRST_TRAIT_COOLDOWN = 56;


	/** RESOURCE_RELATED */
	static const int FIRST_LAYER_FIRST_TRAIT_RESOURCE_RELATED = 57;
	static const int SECOND_LAYER_FIRST_TRAIT_RESOURCE = 58;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALTH = 59;
	static const int THIRD_LAYER_FIRST_TRAIT_MANA = 60;
	static const int THIRD_LAYER_FIRST_TRAIT_SHIELD = 61;
	static const int SECOND_LAYER_FIRST_TRAIT_RESOURCE_RECOVERY = 62;
	static const int THIRD_LAYER_FIRST_TRAIT_REGEN = 63;
	static const int FOURTH_LAYER_FIRST_TRAIT_HEALTH_REGEN = 64;
	static const int FOURTH_LAYER_FIRST_TRAIT_MANA_REGEN = 65;
	static const int FOURTH_LAYER_FIRST_TRAIT_SHIELD_REGEN = 66;
	static const int THIRD_LAYER_FIRST_TRAIT_VAMPIRISM = 67;
	static const int FOURTH_LAYER_FIRST_TRAIT_HEALTH_VAMPIRISM = 68;
	static const int FOURTH_LAYER_FIRST_TRAIT_MANA_VAMPIRISM = 69;
	static const int FOURTH_LAYER_FIRST_TRAIT_SHIELD_VAMPIRISM = 70;


	/** ALTERATION */
	static const int FIRST_LAYER_FIRST_TRAIT_ALTERATION = 71;
	static const int SECOND_LAYER_FIRST_TRAIT_ALTERATION_TYPE = 72;
	static const int THIRD_LAYER_FIRST_TRAIT_DURATION = 73;
	static const int THIRD_LAYER_FIRST_TRAIT_POTENCY = 74;
	static const int THIRD_LAYER_FIRST_TRAIT_URGENCY = 75;
	static const int SECOND_LAYER_SECOND_TRAIT_BENEFICIAL = 76;
	static const int SECOND_LAYER_SECOND_TRAIT_DETRIMENTAL = 77;
};

