#pragma once

class TraitConstants
{
public:
	/** AFFECT */
	static const int FIRST_LAYER_FIRST_TRAIT_AFFECT;
	static const int SECOND_LAYER_FIRST_TRAIT_AFFECT_TYPE;
	static const int THIRD_LAYER_FIRST_TRAIT_AFFECT_TYPE1;
	static const int FOURTH_LAYER_FIRST_TRAIT_DIRECT;
	static const int THIRD_LAYER_FIRST_TRAIT_AFFECT_TYPE2;
	static const int FOURTH_LAYER_FIRST_TRAIT_SINGLE_TARGET;
	static const int FOURTH_LAYER_FIRST_TRAIT_AREA_OF_EFFECT;
	static const int FIFTH_LAYER_FIRST_TRAIT_RADIUS;
	static const int FIFTH_LAYER_FIRST_TRAIT_POWER;
	static const int SECOND_LAYER_SECOND_TRAIT_DAMAGE;
	static const int THIRD_LAYER_FIRST_TRAIT_DAMAGE;
	static const int THIRD_LAYER_FIRST_TRAIT_DAMAGE_TYPE;
	static const int FOURTH_LAYER_FIRST_TRAIT_DAMAGE_TYPE1;
	static const int FIFTH_LAYER_FIRST_TRAIT_PHYSICAL;
	static const int FIFTH_LAYER_FIRST_TRAIT_SUPERNATURAL;
	static const int FOURTH_LAYER_FIRST_TRAIT_DAMAGE_TYPE2;
	static const int FIFTH_LAYER_FIRST_TRAIT_ELEMENTAL;
	static const int SIXTH_LAYER_FIRST_TRAIT_FIRE;
	static const int SIXTH_LAYER_FIRST_TRAIT_FROST;
	static const int SIXTH_LAYER_FIRST_TRAIT_LIGHTNING;
	static const int FIFTH_LAYER_FIRST_TRAIT_PSYCHIC;
	static const int FIFTH_LAYER_FIRST_TRAIT_SOUND;
	static const int FIFTH_LAYER_FIRST_TRAIT_KINETIC;
	static const int FIFTH_LAYER_FIRST_TRAIT_ACID;
	static const int FIFTH_LAYER_FIRST_TRAIT_BLEED;
	static const int FIFTH_LAYER_FIRST_TRAIT_NECROTIC;
	static const int FIFTH_LAYER_FIRST_TRAIT_HOLY;
	static const int FIFTH_LAYER_FIRST_TRAIT_UNHALLOW;
	static const int SECOND_LAYER_SECOND_TRAIT_HEALING;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALING;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALING_TYPE;
	static const int FOURTH_LAYER_FIRST_TRAIT_RESTORATION;
	static const int FOURTH_LAYER_FIRST_TRAIT_ABSORPTION;


	/** STATS */
	static const int FIRST_LAYER_FIRST_TRAIT_STATS;
	static const int SECOND_LAYER_FIRST_TRAIT_OFFENSIVE;
	static const int THIRD_LAYER_FIRST_TRAIT_ATTACK_SPEED;
	static const int THIRD_LAYER_FIRST_TRAIT_CAST_SPEED;
	static const int THIRD_LAYER_FIRST_TRAIT_CRITICAL;
	static const int FOURTH_LAYER_FIRST_TRAIT_CRITICAL_CHANCE;
	static const int FIFTH_LAYER_FIRST_TRAIT_CRITICAL_CHANCE;
	static const int FOURTH_LAYER_FIRST_TRAIT_CRITICAL_EFFECT;
	static const int FIFTH_LAYER_FIRST_TRAIT_CRITICAL_EFFECT;
	static const int THIRD_LAYER_FIRST_TRAIT_HIT_CHANCE;
	static const int FIFTH_LAYER_FIRST_TRAIT_HIT_CHANCE;
	static const int SECOND_LAYER_FIRST_TRAIT_DEFENSIVE;
	static const int THIRD_LAYER_FIRST_TRAIT_EVASION;
	static const int FOURTH_LAYER_FIRST_TRAIT_EVASION_CHANCE;
	static const int THIRD_LAYER_FIRST_TRAIT_DODGE;
	static const int FOURTH_LAYER_FIRST_TRAIT_DODGE_CHANCE;
	static const int FOURTH_LAYER_FIRST_TRAIT_DODGE_REDUCTION;
	static const int THIRD_LAYER_FIRST_TRAIT_BLOCK;
	static const int FOURTH_LAYER_FIRST_TRAIT_BLOCK_CHANCE;
	static const int FOURTH_LAYER_FIRST_TRAIT_BLOCK_REDUCTION;
	static const int THIRD_LAYER_FIRST_TRAIT_ARMOUR;
	static const int FOURTH_LAYER_FIRST_TRAIT_ARMOUR;
	static const int SECOND_LAYER_FIRST_TRAIT_MOVEMENT_SPEED;
	static const int SECOND_LAYER_FIRST_TRAIT_COOLDOWN;


	/** RESOURCE RELATED */
	static const int FIRST_LAYER_FIRST_TRAIT_RESOURCE_RELATED;
	static const int SECOND_LAYER_FIRST_TRAIT_RESOURCE;
	static const int THIRD_LAYER_FIRST_TRAIT_HEALTH;
	static const int THIRD_LAYER_FIRST_TRAIT_MANA;
	static const int THIRD_LAYER_FIRST_TRAIT_SHIELD;
	static const int SECOND_LAYER_FIRST_TRAIT_RESOURCE_RECOVERY;
	static const int THIRD_LAYER_FIRST_TRAIT_REGEN;
	static const int FOURTH_LAYER_FIRST_TRAIT_HEALTH_REGEN;
	static const int FOURTH_LAYER_FIRST_TRAIT_MANA_REGEN;
	static const int FOURTH_LAYER_FIRST_TRAIT_SHIELD_REGEN;
	static const int THIRD_LAYER_FIRST_TRAIT_VAMPIRISM;
	static const int FOURTH_LAYER_FIRST_TRAIT_HEALTH_VAMPIRISM;
	static const int FOURTH_LAYER_FIRST_TRAIT_MANA_VAMPIRISM;
	static const int FOURTH_LAYER_FIRST_TRAIT_SHIELD_VAMPIRISM;


	/** ALTERATION */
	static const int FIRST_LAYER_FIRST_TRAIT_ALTERATION;
	static const int SECOND_LAYER_FIRST_TRAIT_ALTERATION_TYPE;
	static const int THIRD_LAYER_FIRST_TRAIT_DURATION;
	static const int THIRD_LAYER_FIRST_TRAIT_POTENCY;
	static const int THIRD_LAYER_FIRST_TRAIT_URGENCY;
	static const int SECOND_LAYER_SECOND_TRAIT_BENEFICIAL;
	static const int SECOND_LAYER_SECOND_TRAIT_DETRIMENTAL;
};

